### ISSUE TITLE
코코봇 카카오톡 광고관리 제안

### ISSUE THREAD

**Issue by cpprhtn** [easycastle/CoCoBot#2]
코코봇에게 원할때 랜덤코드를 부여받는 함수 제작

랜덤코드를 생성하면 사용자에게 알려주고, 그 코드는 빈 list에 추가

1일이 지나거나, 아니면 카카오톡 log방에서 해당코드가 사용되었을시 list의 해당코드를 제거

당연히 카카오톡에서 허락받아 홍보하는 사람은 해당 코드를 맨 처음에 기재해야한다

**Comment by cocoquiet** [comment]
가장 큰 문제가 카톡코코봇은 태블릿으로 운영된다는 점입니다. 여러가지 고민을 많이 해봤지만 정식 카카오 노드를 쓰는 것 말고는 안정적으로 리스트를 담아내기 힘들것 같은데 태블릿 안에서 안정적으로 랜덤 코드를 부여받는 방법은 뭐가 있을까요?(물론 이건 태블릿에 연결된 인터넷과도 많은 문제가 있습니다)
