### ISSUE TITLE
욕설 감지및 경고 기능 추가 제안

### ISSUE THREAD

**Issue by minecode0606** [easycastle/CoCoBot#3]
tensorflow나 tensorflow.js를 활용하여 코코봇에 자연언어이해(NLU) 알고리즘을 활용한 욕설 감지 인공지능을 추가하여 더욱 정확하게 욕설을 잡을수 있는 기능이 추가되었으면 좋겠습니다 ^^7

**Comment by cocoquiet** [comment]
욕설감지 인공지능을 추가할 시 이벤트 리스너가 많이 사용될거고 그렇게 되면 코코봇의 동작 속도가 매우 느려질 것 같은데 그 점은 어떻게 보완하면 좋을까요?
