### ISSUE TITLE
코코봇 오목판 초기화 버그이슈

### ISSUE THREAD

**Issue by minecode0606** [easycastle/CoCoBot#6]
<img width="876" alt="스크린샷 2021-05-08 오후 11 43 20" src="https://user-images.githubusercontent.com/74087500/117543299-2d161f80-b057-11eb-9e5b-5077df3170b5.png">

2021년 5월 8일경 삽만두님이랑 오목을 두던 중, 게임이 끝났는데도 불구하고 오목판이 초기화가 안되는 버그가 발생하여 제보드립니다.

**Comment by cocoquiet** [comment]
친절한 제보 매우매우 감사드립니다

**Comment by minecode0606** [comment]
^^7
